[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Partition: 2MB app, 1.5MB LittleFS, NVS
board_build.partitions = default_8MB.csv

; Enable PSRAM
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCONFIG_NIMBLE_CPP_ATT_VALUE_INIT_LENGTH=512
    -DCORE_DEBUG_LEVEL=1

; LittleFS for data partition
board_build.filesystem = littlefs

lib_deps =
    zeed/ESP Async WebServer@1.2.3
    zeed/AsyncTCP@1.1.1
    h2zero/NimBLE-Arduino@2.1.2
    bblanchon/ArduinoJson@7.4.2

monitor_speed = 115200
upload_speed = 921600
